### PR TITLE
Add optional AWS SES email on deployments

### PR DESCRIPTION
**Pull request by dmaloneycalu**
Based on @jrit's fork, I made a few variable and naming changes and accounted for the `env` setup, no changes yet to the email template.

Wanted to keep this separate from the other `dominatr-grunt` PR since it was a new addition. Thoughts are welcome.

### CODE REVIEW

**Comment by jrit** [comment]
Did you mean to make a PR against your own fork?

**Comment by dmaloneycalu** [comment]
haha, yes. I wanted to keep these separate from the other mess so that it could be looked at individually

**Comment by dmaloneycalu** [comment]
@jrit Included the updated README documentation in this PR. Let me know if you approve of it

**Comment by jrit** [comment]
I'd like to avoid a situation where it is optional to not send the notifications since we want those emails to be guaranteed to notify relevant team members and so we have a record of all deployments. Can you just move the notification task back into the deploy task?

**Comment by dmaloneycalu** [comment]
@jrit re-added to deploy default and updated the README

**Comment by jrit** [comment]
LGTM

**Comment by jrit** [comment]
I can't merge because I don't have write access on your fork :fried_shrimp:

**Pull request merged**
